name = "kelulusan-backend"
main = "server/index.ts"
compatibility_date = "2024-02-22"

[[d1_databases]]
binding = "DB"
database_name = "kelulusan-d1"
database_id = "7e4892c0-444c-491d-acb8-34b58b168d77"
